'use strict';
const $ = id => document.getElementById(id);
let db, sessions = [], editing = null;
function endDate(start){const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+2);return dateString(d);}
function blockRange(start){const f=new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short',year:'numeric'});return f.format(new Date(start+'T12:00:00'))+' – '+f.format(new Date(endDate(start)+'T12:00:00'));}
function blockHelp(){$('block-range').textContent=$('block-start').value?blockRange($('block-start').value):'';}
function blockOf(s){return s.blockStart||dateString(new Date(s.datetime));}
function updateBlocks(){const previous=$('window').value;const blocks=[...new Set(sessions.map(blockOf))].sort().reverse();$('window').replaceChildren();for(const start of blocks){const option=node('option',blockRange(start));option.value=start;$('window').append(option);}if(blocks.includes(previous))$('window').value=previous;}
$('block-start').addEventListener('change',blockHelp);
const fmt = new Intl.DateTimeFormat('da-DK', {day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
const round = n => Math.round(n);
const average = readings => Object.fromEntries(['sys','dia','pulse'].map(k => [k, readings.reduce((s,r)=>s+r[k],0)/readings.length]));
function message(text){$('message').textContent=text;}
function dateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function resetForm(){editing=null;$('session-form').reset();const now=new Date();$('date').value=dateString(now);const latest=sessions[0]&&blockOf(sessions[0]);$('block-start').value=latest&&dateString(now)>=latest&&dateString(now)<=endDate(latest)?latest:dateString(now);blockHelp();$('time').value=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;document.querySelector(`[name=period][value=${now.getHours()<12?'morgen':'aften'}]`).checked=true;$('save').textContent='Gem målerunde';$('cancel-edit').hidden=true;live();}
function view(name){for(const n of ['register','history'])$(n).hidden=n!==name;document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(name==='history')render();}
for(let i=0;i<3;i++){$('rows').insertAdjacentHTML('beforeend',`<div class="measurement-row"><span>${i+1}</span>${[['sys','Overtryk',40,300],['dia','Undertryk',20,200],['pulse','Puls',20,250]].map(([k,label,min,max])=>`<input id="${k}-${i}" type="number" inputmode="numeric" min="${min}" max="${max}" step="1" required aria-label="${label}, måling ${i+1}" placeholder="—">`).join('')}</div>`);}
function getReadings(){return [0,1,2].map(i=>Object.fromEntries(['sys','dia','pulse'].map(k=>[k,Number($(`${k}-${i}`).value)])));}
function validReadings(rs){return Array.isArray(rs)&&rs.length===3&&rs.every(r=>r&&[['sys',40,300],['dia',20,200],['pulse',20,250]].every(([k,lo,hi])=>Number.isInteger(r[k])&&r[k]>=lo&&r[k]<=hi)&&r.sys>r.dia);}
function live(){const complete=getReadings().filter(r=>r.sys&&r.dia&&r.pulse);if(!complete.length){$('live-bp').textContent='— / —';$('live-pulse').textContent='Indtast dine tre målinger';return;}const a=average(complete);$('live-bp').textContent=`${round(a.sys)} / ${round(a.dia)}`;$('live-pulse').textContent=`Puls ${round(a.pulse)} · ${complete.length} af 3 målinger`;}
$('rows').addEventListener('input',live);
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('mit-blodtryk',1);req.onupgradeneeded=()=>req.result.createObjectStore('sessions',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Luk andre faner med appen, og prøv igen.'));});}
function transaction(mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction('sessions',mode);action(tx.objectStore('sessions'));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function load(){return new Promise((resolve,reject)=>{const req=db.transaction('sessions').objectStore('sessions').getAll();req.onsuccess=()=>{sessions=req.result.sort((a,b)=>b.datetime.localeCompare(a.datetime));resolve();};req.onerror=()=>reject(req.error);});}
$('session-form').addEventListener('submit',async e=>{e.preventDefault();if(!db)return;const readings=getReadings();if(!validReadings(readings)){message('Tjek tallene: overtrykket skal være højere end undertrykket i hver måling.');return;}if(!/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test($('time').value)){message('Skriv tiden i 24-timers format, fx 08:30 eller 20:30.');return;}const datetime=new Date(`${$('date').value}T${$('time').value}`);if(!Number.isFinite(datetime.getTime())){message('Vælg en gyldig dato og tid.');return;}const blockStart=$('block-start').value;const measurementDate=$('date').value;if(measurementDate<blockStart||measurementDate>endDate(blockStart)){message('Måledatoen skal ligge i den valgte 3-dages session.');return;}const record={blockStart,id:editing||crypto.randomUUID(),datetime:datetime.toISOString(),period:document.querySelector('[name=period]:checked').value,readings,note:$('note').value.trim()};$('save').disabled=true;try{await transaction('readwrite',store=>store.put(record));await load();updateBlocks();$('window').value=blockStart;resetForm();view('history');message('Målerunden er gemt i din 3-dages session.');}catch{message('Kunne ikke gemme. Behold tallene, og prøv igen.');}finally{$('save').disabled=false;}});
$('cancel-edit').onclick=()=>{resetForm();message('');};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>view(b.dataset.view));$('window').onchange=render;
function selected(){return sessions.filter(s=>blockOf(s)===$('window').value);}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function render(){const subset=selected();const all=subset.flatMap(s=>s.readings);if(all.length){const a=average(all);$('summary-bp').textContent=`${round(a.sys)} / ${round(a.dia)}`;$('summary-meta').textContent=`Puls ${round(a.pulse)} · ${subset.length} målerunder · ${all.length} målinger · ${new Set(subset.map(s=>dateString(new Date(s.datetime)))).size} af 3 dage`;}else{$('summary-bp').textContent='— / —';$('summary-meta').textContent='Ingen målinger i denne session';}$('count').textContent=`${subset.length} målerunder`;$('sessions').replaceChildren();if(!subset.length)$('sessions').append(node('p','Dine 3-dages sessioner vises her. Start med en ny målerunde.','empty'));for(const s of subset){const a=average(s.readings);const card=node('article',undefined,'session');const top=node('div',undefined,'session-top');const title=node('div');title.append(node('h4',s.period==='morgen'?'Morgen':'Aften'));const time=node('time',fmt.format(new Date(s.datetime)));time.dateTime=s.datetime;title.append(time);top.append(title,node('div',`${round(a.sys)} / ${round(a.dia)}`,'session-bp'));card.append(top,node('p',`Puls ${round(a.pulse)} · Gennemsnit af 3 målinger`,'meta'));if(s.note)card.append(node('p',s.note,'note'));const details=node('details');details.append(node('summary','Se de tre målinger'));const table=node('table');table.innerHTML='<thead><tr><th>Måling</th><th>Overtryk</th><th>Undertryk</th><th>Puls</th></tr></thead>';const body=node('tbody');s.readings.forEach((r,i)=>{const tr=node('tr');[i+1,r.sys,r.dia,r.pulse].forEach(v=>tr.append(node('td',v)));body.append(tr);});table.append(body);details.append(table);card.append(details);const actions=node('div',undefined,'session-actions');const edit=node('button','Rediger','secondary');edit.onclick=()=>editSession(s);const del=node('button','Slet','secondary');del.onclick=async()=>{if(!confirm('Slet denne målerunde?'))return;try{await transaction('readwrite',store=>store.delete(s.id));await load();updateBlocks();render();message('Målerunden er slettet.');}catch{message('Kunne ikke slette målerunden.');}};actions.append(edit,del);card.append(actions);$('sessions').append(card);}chart(subset);}
function editSession(s){editing=s.id;$('block-start').value=blockOf(s);blockHelp();const d=new Date(s.datetime);$('date').value=dateString(d);$('time').value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;document.querySelector(`[name=period][value=${s.period}]`).checked=true;s.readings.forEach((r,i)=>['sys','dia','pulse'].forEach(k=>$(`${k}-${i}`).value=r[k]));$('note').value=s.note;$('save').textContent='Gem ændringer';$('cancel-edit').hidden=false;live();view('register');window.scrollTo({top:0,behavior:'smooth'});}
function chart(subset){$('chart').replaceChildren();if(!subset.length){$('chart').append(node('p','Grafen vises, når du har gemt en målerunde.'));return;}const points=[...subset].reverse().map(s=>({...average(s.readings),date:new Date(s.datetime)}));const min=Math.floor((Math.min(...points.map(p=>p.dia))-10)/10)*10;const max=Math.ceil((Math.max(...points.map(p=>p.sys))+10)/10)*10;const w=600,h=250,l=42,r=18,t=18,b=34;const x=i=>points.length===1?w/2:l+i*(w-l-r)/(points.length-1);const y=v=>t+(max-v)/(max-min)*(h-t-b);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Blodtryk pr. målerunde, fra ældste til nyeste. Tallene kan også ses i historikken.');let content='';for(let i=0;i<5;i++){const v=min+(max-min)*i/4;content+=`<line x1="${l}" y1="${y(v)}" x2="${w-r}" y2="${y(v)}" stroke="#e5e9f1"/><text x="${l-8}" y="${y(v)+4}" text-anchor="end" fill="#5c6980" font-size="13">${round(v)}</text>`;}for(const [k,color] of [['sys','#173fdf'],['dia','#cd5086']]){content+=`<polyline fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round" points="${points.map((p,i)=>`${x(i)},${y(p[k])}`).join(' ')}"/>`;points.forEach((p,i)=>{content+=`<circle cx="${x(i)}" cy="${y(p[k])}" r="4" fill="${color}"><title>${fmt.format(p.date)}: ${round(p[k])} mmHg</title></circle>`;});}const df=new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short'});content+=`<text x="${l}" y="${h-7}" fill="#5c6980" font-size="13">${df.format(points[0].date)}</text>`;if(points.length>1)content+=`<text x="${w-r}" y="${h-7}" text-anchor="end" fill="#5c6980" font-size="13">${df.format(points.at(-1).date)}</text>`;svg.innerHTML=content;$('chart').append(svg);}
function download(content,type,name){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('export').onclick=()=>{if(!db){message('Data er ikke tilgængelige.');return;}download(JSON.stringify({app:'mit-blodtryk',version:1,exportedAt:new Date().toISOString(),sessions},null,2),'application/json',`blodtryk-backup-${dateString(new Date())}.json`);};
$('csv').onclick=()=>{const quote=v=>'"'+String(v).replaceAll('"','""')+'"';const safe=v=>/^[=+@\-\t\r\n]/.test(v)?"'"+v:v;const lines=[['Sessionens startdato','Dato og tid','Morgen/aften','Måling','Overtryk','Undertryk','Puls','Note'],...sessions.flatMap(s=>s.readings.map((r,i)=>[blockOf(s),fmt.format(new Date(s.datetime)),s.period,i+1,r.sys,r.dia,r.pulse,safe(s.note)]))];download('\ufeff'+lines.map(row=>row.map(quote).join(';')).join('\r\n'),'text/csv;charset=utf-8',`blodtryk-${dateString(new Date())}.csv`);};
function validRecord(s){return s&&(!s.blockStart||(/^\d{4}-\d{2}-\d{2}$/.test(s.blockStart)&&Number.isFinite(new Date(s.blockStart+'T12:00:00').getTime())&&dateString(new Date(s.datetime))>=s.blockStart&&dateString(new Date(s.datetime))<=endDate(s.blockStart)))&&typeof s.id==='string'&&/^[a-zA-Z0-9-]{1,100}$/.test(s.id)&&typeof s.datetime==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(s.datetime)&&Number.isFinite(new Date(s.datetime).getTime())&&['morgen','aften'].includes(s.period)&&validReadings(s.readings)&&typeof s.note==='string'&&s.note.length<=1000;}
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(!db)throw new Error('Data er ikke tilgængelige.');if(file.size>10*1024*1024)throw new Error('Backupfilen er for stor (maks. 10 MB).');const data=JSON.parse(await file.text());if(data.app!=='mit-blodtryk'||data.version!==1||!Array.isArray(data.sessions)||!data.sessions.every(validRecord)||new Set(data.sessions.map(s=>s.id)).size!==data.sessions.length)throw new Error('Filen er ikke en gyldig blodtryksbackup.');const existing=new Set(sessions.map(s=>s.id));const additions=data.sessions.filter(s=>!existing.has(s.id)).map(s=>({id:s.id,blockStart:blockOf(s),datetime:new Date(s.datetime).toISOString(),period:s.period,readings:s.readings.map(r=>({sys:r.sys,dia:r.dia,pulse:r.pulse})),note:s.note}));if(!confirm(`Indlæs ${additions.length} nye målerunder? Eksisterende målerunder beholdes. Målerunder med samme ID springes over.`))return;await transaction('readwrite',store=>additions.forEach(s=>store.add(s)));await load();updateBlocks();render();view('history');message(`${additions.length} målerunder indlæst. Eksisterende målerunder er bevaret.`);}catch(err){message(err.message||'Kunne ikke indlæse backup.');}finally{e.target.value='';}};
async function init(){resetForm();$('save').disabled=true;try{db=await openDB();await load();updateBlocks();resetForm();render();$('save').disabled=false;}catch{message('Lokal lagring kunne ikke åbnes. Prøv almindelig Safari, og kontrollér ledig plads.');}if('serviceWorker' in navigator&&window.isSecureContext){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offline').textContent='Appen er klar til offlinebrug på denne adresse.';}catch{$('offline').textContent='Offline-klargøring mislykkedes. Åbn appen igen med internet.';}}}
init();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_blood_pressure_overview',description:'Vis overblikket for en 3-dages session valgt efter startdato.',inputSchema:{type:'object',properties:{startDate:{type:'string'}},required:['startDate'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({startDate})=>{if(!sessions.some(s=>blockOf(s)===startDate))throw new Error('Ukendt session');$('window').value=startDate;view('history');return {measurementRounds:selected().length,startDate};}})).catch(()=>{});}catch{}}
