import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, collection, doc, getDocsFromServer, setDoc, deleteDoc, runTransaction } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
const firebaseConfig = {
 apiKey: 'AIzaSyDeEZ58vfxDU0neT3VeiLWD3VSPpnSCd7w',
 authDomain: 'blodtryk-a1472.firebaseapp.com',
 projectId: 'blodtryk-a1472',
 storageBucket: 'blodtryk-a1472.firebasestorage.app',
 messagingSenderId: '51098602742',
 appId: '1:51098602742:web:8517820c1017b08f8770d7'
};
const firebaseApp=initializeApp(firebaseConfig);
const auth=getAuth(firebaseApp), cloud=getFirestore(firebaseApp);
let currentUser=null, accountEpoch=0, cloudLoaded=false;
function requireAccount(){if(!currentUser)throw new Error('Log ind med Google først.');if(!navigator.onLine)throw new Error('Du er offline. Opret forbindelse for at gemme i Firebase.');return currentUser.uid;}
function cloudRef(uid,id){return doc(cloud,'users',uid,'sessions',id);}
function cloudError(error){const code=error?.code||'';if(code.includes('permission-denied'))return 'Adgang afvist. Kontrollér Firestore-reglerne i Firebase.';if(code.includes('unauthorized-domain'))return 'Tilføj GitHub Pages-domænet under Authentication → Settings → Authorized domains.';if(code.includes('operation-not-allowed'))return 'Aktivér Google-login under Authentication i Firebase.';if(code.includes('popup-blocked'))return 'Tillad loginvinduet i Safari, og prøv igen.';if(code.includes('popup-closed-by-user'))return 'Login blev lukket. Prøv igen.';return error?.message||'Kunne ikke forbinde til Firebase. Prøv igen.';}
async function writeRecord(record){const uid=requireAccount();await setDoc(cloudRef(uid,record.id),record);return uid;}
async function addRecords(records){const uid=requireAccount();let added=0;for(const record of records){if(currentUser?.uid!==uid)throw new Error('Kontoen er ændret. Start importen igen.');const ref=cloudRef(uid,record.id);const didAdd=await runTransaction(cloud,async tx=>{const existing=await tx.get(ref);if(existing.exists())return false;tx.set(ref,record);return true;});if(didAdd)added++;}if(currentUser?.uid!==uid)throw new Error('Kontoen er ændret.');return added;}

const $ = id => document.getElementById(id);
function formatTimeInput(value){const digits=value.replace(/[^0-9]/g,'').slice(0,4);return digits.length>2?digits.slice(0,2)+':'+digits.slice(2):digits;}
$('time').addEventListener('input',event=>{const input=event.target;const original=input.value;const caret=input.selectionStart??original.length;const digitsBefore=original.slice(0,caret).replace(/[^0-9]/g,'').length;input.value=formatTimeInput(original);const nextCaret=Math.min(input.value.length,digitsBefore+(digitsBefore>2?1:0));input.setSelectionRange(nextCaret,nextCaret);});
let sessions = [], editing = null;

function displayDate(iso){return iso.split('-').reverse().join('.');}
function parseDate(value){const m=/^(\d{2})\.(\d{2})\.(\d{4})$/.exec(value);if(!m)return '';const iso=`${m[3]}-${m[2]}-${m[1]}`;const d=new Date(iso+'T12:00:00');return Number.isFinite(d.getTime())&&dateString(d)===iso?iso:'';}
function formatDateInput(value){const d=value.replace(/[^0-9]/g,'').slice(0,8);return d.slice(0,2)+(d.length>2?'.'+d.slice(2,4):'')+(d.length>4?'.'+d.slice(4):'');}
for(const id of ['date','block-start'])$(id).addEventListener('input',event=>{const input=event.target;const original=input.value;const caret=input.selectionStart??original.length;const n=original.slice(0,caret).replace(/[^0-9]/g,'').length;input.value=formatDateInput(original);const next=Math.min(input.value.length,n+(n>2?1:0)+(n>4?1:0));input.setSelectionRange(next,next);input.setCustomValidity(input.value.length===10&&!parseDate(input.value)?'Indtast en gyldig dato som dd.mm.åååå.':'');if(id==='block-start')blockHelp();});

function endDate(start){const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+2);return dateString(d);}
function blockRange(start){const f=new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short',year:'numeric'});return f.format(new Date(start+'T12:00:00'))+' – '+f.format(new Date(endDate(start)+'T12:00:00'));}
function blockHelp(){const start=parseDate($('block-start').value);$('block-range').textContent=start?blockRange(start):'';}
function blockOf(s){return s.blockStart||dateString(new Date(s.datetime));}
function updateBlocks(){const previous=$('window').value;const blocks=[...new Set(sessions.map(blockOf))].sort().reverse();$('window').replaceChildren();for(const start of blocks){const option=node('option',blockRange(start));option.value=start;$('window').append(option);}if(blocks.includes(previous))$('window').value=previous;}
$('block-start').addEventListener('change',blockHelp);
const fmt = new Intl.DateTimeFormat('da-DK', {day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
const round = n => Math.round(n);
const average = readings => Object.fromEntries(['sys','dia','pulse'].map(k => [k, readings.reduce((s,r)=>s+r[k],0)/readings.length]));
function message(text){$('message').textContent=text;}
function dateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function resetForm(){for(const id of ['date','block-start'])$(id).setCustomValidity('');editing=null;$('session-form').reset();const now=new Date();$('date').value=displayDate(dateString(now));const latest=sessions[0]&&blockOf(sessions[0]);$('block-start').value=displayDate(latest&&dateString(now)>=latest&&dateString(now)<=endDate(latest)?latest:dateString(now));blockHelp();$('time').value=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;document.querySelector(`[name=period][value=${now.getHours()<12?'morgen':'aften'}]`).checked=true;$('save').textContent='Gem målerunde';$('cancel-edit').hidden=true;live();}
function view(name){for(const n of ['register','history'])$(n).hidden=n!==name;document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(name==='history')render();}
for(let i=0;i<3;i++){$('rows').insertAdjacentHTML('beforeend',`<div class="measurement-row"><span>${i+1}</span>${[['sys','Overtryk',40,300],['dia','Undertryk',20,200],['pulse','Puls',20,250]].map(([k,label,min,max])=>`<input id="${k}-${i}" type="number" inputmode="numeric" min="${min}" max="${max}" step="1" required aria-label="${label}, måling ${i+1}" placeholder="—">`).join('')}</div>`);}
function getReadings(){return [0,1,2].map(i=>Object.fromEntries(['sys','dia','pulse'].map(k=>[k,Number($(`${k}-${i}`).value)])));}
function validReadings(rs){return Array.isArray(rs)&&rs.length===3&&rs.every(r=>r&&[['sys',40,300],['dia',20,200],['pulse',20,250]].every(([k,lo,hi])=>Number.isInteger(r[k])&&r[k]>=lo&&r[k]<=hi)&&r.sys>r.dia);}
function live(){const complete=getReadings().filter(r=>r.sys&&r.dia&&r.pulse);if(!complete.length){$('live-bp').textContent='— / —';$('live-pulse').textContent='Indtast dine tre målinger';return;}const a=average(complete);$('live-bp').textContent=`${round(a.sys)} / ${round(a.dia)}`;$('live-pulse').textContent=`Puls ${round(a.pulse)} · ${complete.length} af 3 målinger`;}
$('rows').addEventListener('input',live);
async function load(){const uid=requireAccount();const epoch=accountEpoch;const result=await getDocsFromServer(collection(cloud,'users',uid,'sessions'));if(epoch!==accountEpoch||currentUser?.uid!==uid)throw new Error('Kontoen er ændret.');cloudLoaded=true;sessions=result.docs.map(d=>({...d.data(),id:d.id})).filter(validRecord).sort((a,b)=>b.datetime.localeCompare(a.datetime));}
$('session-form').addEventListener('submit',async e=>{e.preventDefault();if(!currentUser){message('Log ind med Google først.');return;}const readings=getReadings();if(!validReadings(readings)){message('Tjek tallene: overtrykket skal være højere end undertrykket i hver måling.');return;}if(!/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test($('time').value)){message('Skriv tiden i 24-timers format, fx 08:30 eller 20:30.');return;}const measurementDate=parseDate($('date').value);const blockStart=parseDate($('block-start').value);if(!measurementDate||!blockStart){message('Indtast en gyldig dato i formatet dd.mm.åååå.');return;}const datetime=new Date(`${measurementDate}T${$('time').value}`);if(!Number.isFinite(datetime.getTime())){message('Vælg en gyldig dato og tid.');return;}if(measurementDate<blockStart||measurementDate>endDate(blockStart)){message('Måledatoen skal ligge i den valgte 3-dages session.');return;}const record={blockStart,id:editing||crypto.randomUUID(),datetime:datetime.toISOString(),period:document.querySelector('[name=period]:checked').value,readings,note:$('note').value.trim()};$('save').disabled=true;message('Gemmer i Firebase… Vent på bekræftelsen, før du lukker appen.');try{const savedUid=await writeRecord(record);if(currentUser?.uid!==savedUid)return;sessions=sessions.filter(s=>s.id!==record.id);sessions.push(record);sessions.sort((a,b)=>b.datetime.localeCompare(a.datetime));updateBlocks();$('window').value=blockStart;resetForm();view('history');message('Gemt i Firebase · Målerunden er gemt online.');}catch(error){message(cloudError(error)+' Tallene er beholdt i formularen.');}finally{$('save').disabled=!currentUser;}});
$('cancel-edit').onclick=()=>{resetForm();message('');};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>view(b.dataset.view));$('window').onchange=render;
function selected(){return sessions.filter(s=>blockOf(s)===$('window').value);}
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function render(){const subset=selected();const all=subset.flatMap(s=>s.readings);if(all.length){const a=average(all);$('summary-bp').textContent=`${round(a.sys)} / ${round(a.dia)}`;$('summary-meta').textContent=`Puls ${round(a.pulse)} · ${subset.length} målerunder · ${all.length} målinger · ${new Set(subset.map(s=>dateString(new Date(s.datetime)))).size} af 3 dage`;}else{$('summary-bp').textContent='— / —';$('summary-meta').textContent='Ingen målinger i denne session';}$('count').textContent=`${subset.length} målerunder`;$('sessions').replaceChildren();if(!subset.length)$('sessions').append(node('p','Dine 3-dages sessioner vises her. Start med en ny målerunde.','empty'));for(const s of subset){const a=average(s.readings);const card=node('article',undefined,'session');const top=node('div',undefined,'session-top');const title=node('div');title.append(node('h4',s.period==='morgen'?'Morgen':'Aften'));const time=node('time',fmt.format(new Date(s.datetime)));time.dateTime=s.datetime;title.append(time);top.append(title,node('div',`${round(a.sys)} / ${round(a.dia)}`,'session-bp'));card.append(top,node('p',`Puls ${round(a.pulse)} · Gennemsnit af 3 målinger`,'meta'));if(s.note)card.append(node('p',s.note,'note'));const details=node('details');details.append(node('summary','Se de tre målinger'));const table=node('table');table.innerHTML='<thead><tr><th>Måling</th><th>Overtryk</th><th>Undertryk</th><th>Puls</th></tr></thead>';const body=node('tbody');s.readings.forEach((r,i)=>{const tr=node('tr');[i+1,r.sys,r.dia,r.pulse].forEach(v=>tr.append(node('td',v)));body.append(tr);});table.append(body);details.append(table);card.append(details);const actions=node('div',undefined,'session-actions');const edit=node('button','Rediger','secondary');edit.onclick=()=>editSession(s);const del=node('button','Slet','secondary');del.onclick=async()=>{if(!confirm('Slet denne målerunde?'))return;try{const uid=requireAccount();await deleteDoc(cloudRef(uid,s.id));if(currentUser?.uid!==uid)return;sessions=sessions.filter(r=>r.id!==s.id);updateBlocks();render();message('Målerunden er slettet.');}catch(error){message(cloudError(error));}};actions.append(edit,del);card.append(actions);$('sessions').append(card);}chart(subset);}
function editSession(s){for(const id of ['date','block-start'])$(id).setCustomValidity('');editing=s.id;$('block-start').value=displayDate(blockOf(s));blockHelp();const d=new Date(s.datetime);$('date').value=displayDate(dateString(d));$('time').value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;document.querySelector(`[name=period][value=${s.period}]`).checked=true;s.readings.forEach((r,i)=>['sys','dia','pulse'].forEach(k=>$(`${k}-${i}`).value=r[k]));$('note').value=s.note;$('save').textContent='Gem ændringer';$('cancel-edit').hidden=false;live();view('register');window.scrollTo({top:0,behavior:'smooth'});}
function chart(subset){$('chart').replaceChildren();if(!subset.length){$('chart').append(node('p','Grafen vises, når du har gemt en målerunde.'));return;}const points=[...subset].reverse().map(s=>({...average(s.readings),date:new Date(s.datetime)}));const min=Math.floor((Math.min(...points.map(p=>p.dia))-10)/10)*10;const max=Math.ceil((Math.max(...points.map(p=>p.sys))+10)/10)*10;const w=600,h=250,l=42,r=18,t=18,b=34;const x=i=>points.length===1?w/2:l+i*(w-l-r)/(points.length-1);const y=v=>t+(max-v)/(max-min)*(h-t-b);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Blodtryk pr. målerunde, fra ældste til nyeste. Tallene kan også ses i historikken.');let content='';for(let i=0;i<5;i++){const v=min+(max-min)*i/4;content+=`<line x1="${l}" y1="${y(v)}" x2="${w-r}" y2="${y(v)}" stroke="#e5e9f1"/><text x="${l-8}" y="${y(v)+4}" text-anchor="end" fill="#5c6980" font-size="13">${round(v)}</text>`;}for(const [k,color] of [['sys','#173fdf'],['dia','#cd5086']]){content+=`<polyline fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round" points="${points.map((p,i)=>`${x(i)},${y(p[k])}`).join(' ')}"/>`;points.forEach((p,i)=>{content+=`<circle cx="${x(i)}" cy="${y(p[k])}" r="4" fill="${color}"><title>${fmt.format(p.date)}: ${round(p[k])} mmHg</title></circle>`;});}const df=new Intl.DateTimeFormat('da-DK',{day:'numeric',month:'short'});content+=`<text x="${l}" y="${h-7}" fill="#5c6980" font-size="13">${df.format(points[0].date)}</text>`;if(points.length>1)content+=`<text x="${w-r}" y="${h-7}" text-anchor="end" fill="#5c6980" font-size="13">${df.format(points.at(-1).date)}</text>`;svg.innerHTML=content;$('chart').append(svg);}
function download(content,type,name){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('export').onclick=()=>{if(!currentUser||!cloudLoaded){message('Log ind, og hent dine målinger først.');return;}download(JSON.stringify({app:'mit-blodtryk',version:1,exportedAt:new Date().toISOString(),sessions},null,2),'application/json',`blodtryk-backup-${dateString(new Date())}.json`);};
$('csv').onclick=()=>{if(!cloudLoaded){message('Hent dine målinger fra Firebase først.');return;}const quote=v=>'"'+String(v).replaceAll('"','""')+'"';const safe=v=>/^[=+@\-\t\r\n]/.test(v)?"'"+v:v;const lines=[['Sessionens startdato','Dato og tid','Morgen/aften','Måling','Overtryk','Undertryk','Puls','Note'],...sessions.flatMap(s=>s.readings.map((r,i)=>[blockOf(s),fmt.format(new Date(s.datetime)),s.period,i+1,r.sys,r.dia,r.pulse,safe(s.note)]))];download('\ufeff'+lines.map(row=>row.map(quote).join(';')).join('\r\n'),'text/csv;charset=utf-8',`blodtryk-${dateString(new Date())}.csv`);};
function validRecord(s){return s&&(!s.blockStart||(/^\d{4}-\d{2}-\d{2}$/.test(s.blockStart)&&Number.isFinite(new Date(s.blockStart+'T12:00:00').getTime())&&dateString(new Date(s.datetime))>=s.blockStart&&dateString(new Date(s.datetime))<=endDate(s.blockStart)))&&typeof s.id==='string'&&/^[a-zA-Z0-9-]{1,100}$/.test(s.id)&&typeof s.datetime==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(s.datetime)&&Number.isFinite(new Date(s.datetime).getTime())&&['morgen','aften'].includes(s.period)&&validReadings(s.readings)&&typeof s.note==='string'&&s.note.length<=1000;}
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{requireAccount();if(file.size>10*1024*1024)throw new Error('Backupfilen er for stor (maks. 10 MB).');const data=JSON.parse(await file.text());if(data.app!=='mit-blodtryk'||data.version!==1||!Array.isArray(data.sessions)||!data.sessions.every(validRecord)||new Set(data.sessions.map(s=>s.id)).size!==data.sessions.length)throw new Error('Filen er ikke en gyldig blodtryksbackup.');const existing=new Set(sessions.map(s=>s.id));const additions=data.sessions.filter(s=>!existing.has(s.id)).map(s=>({id:s.id,blockStart:blockOf(s),datetime:new Date(s.datetime).toISOString(),period:s.period,readings:s.readings.map(r=>({sys:r.sys,dia:r.dia,pulse:r.pulse})),note:s.note}));if(!confirm(`Indlæs ${additions.length} nye målerunder? Eksisterende målerunder beholdes. Målerunder med samme ID springes over.`))return;const added=await addRecords(additions);await load();updateBlocks();render();view('history');message(`${added} målerunder gemt i Firebase. Eksisterende målerunder er bevaret.`);}catch(err){message(err.message||'Kunne ikke indlæse backup.');}finally{e.target.value='';}};
async function init(){resetForm();$('save').disabled=true;
 $('login').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(error){message(cloudError(error));}};
 onAuthStateChanged(auth,async user=>{const epoch=++accountEpoch;currentUser=user;cloudLoaded=false;sessions=[];resetForm();updateBlocks();render();$('save').disabled=true;$('login').hidden=!!user;$('account-status').textContent=user?`Logget ind som ${user.email} · henter målinger…`:'Log ind for at gemme og hente dine målinger online.';if(!user)return;try{await load();if(epoch!==accountEpoch)return;updateBlocks();resetForm();render();$('account-status').textContent=`${user.email} · Firebase`;message('Målingerne er hentet fra Firebase.');}catch(error){if(epoch===accountEpoch){$('account-status').textContent=`${user.email} · kunne ikke hente målinger`;message(cloudError(error));}}finally{if(epoch===accountEpoch)$('save').disabled=false;}});
 if('serviceWorker' in navigator&&window.isSecureContext){try{await navigator.serviceWorker.register('./sw.js');}catch{}}
}
init().catch(error=>message(cloudError(error)));

if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'show_blood_pressure_overview',description:'Vis overblikket for en 3-dages session valgt efter startdato.',inputSchema:{type:'object',properties:{startDate:{type:'string'}},required:['startDate'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({startDate})=>{if(!sessions.some(s=>blockOf(s)===startDate))throw new Error('Ukendt session');$('window').value=startDate;view('history');return {measurementRounds:selected().length,startDate};}})).catch(()=>{});}catch{}}
